* Disclaimer

This code has been orginally forked from the Args program described in: http://butunclebob.com/ArticleS.UncleBob.CleanCodeArgs. I have further tried
to implement a clean coding practice on this source written in Java.

* Usage 
To use the code please implement the main class in the following way

#+BEGIN_SRC java
public class ArgsMain {
  public static void main(String[] args) {
    try {
      Args arg = new Args("l,p#,d*", args);
      boolean logging = arg.getBoolean('l');
      int port = arg.getInt('p');
      String directory = arg.getString('d');
      executeApplication(logging, port, directory);
    } catch (ArgsException e) {
      System.out.printf("Argument error: %s\n", e.errorMessage());
    }
  }

  private static void executeApplication(boolean logging, int port, String directory) {
    System.out.printf("logging is %s, port:%d, directory:%s\n",logging, port, directory);
  }
}
#+END_SRC 



* Schema:
 - char    - Boolean arg.
 - char*   - String arg.
 - char#   - Integer arg.
 - char##  - double arg.
 - char[*] - one element of a string array.

Example schema: (f,s*,n#,a##,p[*])
Coresponding command line: "-f -s Bob -n 1 -a 3.2 -p e1 -p e2 -p e3

* Clean Code Practices

The source code makes use of the following clean coding prcatices:-

** Clean Code Practices in Source Code

*** Package
+ The package names are named to convey the semantic categorisation for the classes inside the package.

*** Imports
+ The imports inside the classes have been seperated into groups in the order.
  - java libraries import
  - java libraries static import
  - local libraries
  - local libraries static imports

*** Class / Interface Name
+ The class interfaces names have been named to convey the semantic meaning of the operations / functions defined in the class.
+ The interface names start with an "I" to denote that the file contains the definition of an interface.

*** Variables
+ The variables declared in the classes are arranged alphabetically, so enable reviewer go through each variable in sequence.
+ The variables are named to convey the semantic meaning and importance of the data to be stored.
+ Numbering is used in variables to enable quick and easy reading of the variables and understand their meanings


